<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

define('ISLANDORA_REST_VERSION', 'v1');
define('ISLANDORA_REST_URL_PREFIX', 'islandora/rest/' . ISLANDORA_REST_VERSION);
define('MENU_ISLANDORA_REST_OBJECT', ISLANDORA_REST_URL_PREFIX . '/object');
define('MENU_ISLANDORA_REST_DATASTREAM', MENU_ISLANDORA_REST_OBJECT . '/%/datastream');
define('MENU_ISLANDORA_REST_RELATIONSHIP', MENU_ISLANDORA_REST_OBJECT . '/%/relationship');
define('MENU_ISLANDORA_REST_SOLR', ISLANDORA_REST_URL_PREFIX . '/solr');
define('PERM_OBJECT_GET', 'view objects');
define('PERM_OBJECT_POST', 'create objects');
define('PERM_OBJECT_PUT', 'modify object properties');
define('PERM_OBJECT_DELETE', 'delete objects');
define('PERM_DATASTREAM_GET', 'view datastreams');
define('PERM_DATASTREAM_POST', 'create datastreams');
define('PERM_DATASTREAM_PUT', 'modify datastreams');
define('PERM_DATASTREAM_DELETE', 'delete datastreams');
define('PERM_RELATIONSHIP_GET', 'list relationships');
define('PERM_RELATIONSHIP_POST', 'create relationships');
define('PERM_RELATIONSHIP_DELETE', 'delete relationships');

/**
 * Implements hook_menu().
 */
function islandora_rest_menu() {
  // We don't use the access callback for any of the REST end-poinst as we can't
  // reliably return JSON from that point.
  return array(
    MENU_ISLANDORA_REST_OBJECT => array(
      'page callback' => 'islandora_rest_object',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    MENU_ISLANDORA_REST_DATASTREAM => array(
      'page callback' => 'islandora_rest_datastream',
      'page arguments' => array(4, 6),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    MENU_ISLANDORA_REST_RELATIONSHIP => array(
      'page callback' => 'islandora_rest_relationship',
      'page arguments' => array(4),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    MENU_ISLANDORA_REST_SOLR => array(
      'page callback' => 'islandora_rest_solr',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_rest_permission() {
  return array(
    PERM_OBJECT_GET => array(
      'title' => t('View objects'),
      'description' => t('Allows users to fetch an objects properties and list its datastreams.'),
    ),
    PERM_OBJECT_POST => array(
      'title' => t('Create objects'),
      'description' => t('Allows users to create objects.'),
    ),
    PERM_OBJECT_PUT => array(
      'title' => t('Modify object properties'),
      'description' => t('Allows users to modify an objects properites.'),
    ),
    PERM_OBJECT_DELETE => array(
      'title' => t('Delete objects'),
      'description' => t('Allows users to delete objects.'),
    ),
    PERM_DATASTREAM_GET => array(
      'title' => t('View datastreams'),
      'description' => t('Allows users to get a given datastream content and properties.'),
    ),
    PERM_DATASTREAM_POST => array(
      'title' => t('Create datastreams'),
      'description' => t('Allows users to create datastreams.'),
    ),
    PERM_DATASTREAM_PUT => array(
      'title' => t('Modify datastreams'),
      'description' => t('Allows users to modify existing datastreams and their properties.'),
    ),
    PERM_DATASTREAM_DELETE => array(
      'title' => t('Delete datastreams'),
      'description' => t('Allows users to delete datastreams.'),
    ),
    PERM_RELATIONSHIP_GET => array(
      'title' => t('List relationships'),
      'description' => t('Allows users to list an objects relationships.'),
    ),
    PERM_RELATIONSHIP_POST => array(
      'title' => t('Create relationships'),
      'description' => t('Allows users to create new relationships.'),
    ),
    PERM_RELATIONSHIP_DELETE => array(
      'title' => t('Delete relationships'),
      'description' => t('Allows users to delete existing relationships'),
    ),
  );
}

/**
 * Rest end-point for objects.
 *
 * @note This function exits.
 */
function islandora_rest_object($pid = NULL) {
  module_load_include('inc', 'islandora_rest', 'includes/utilities');
  print islandora_rest_get_response('object', array('pid' => $pid));
  exit();
}

/**
 * Rest end-point for datastreams.
 *
 * @note This function exits.
 */
function islandora_rest_datastream($pid, $dsid = NULL) {
  module_load_include('inc', 'islandora_rest', 'includes/utilities');
  print islandora_rest_get_response('datastream', array('pid' => $pid, 'dsid' => $dsid));
  exit();
}

/**
 * Rest end-point for relationships.
 *
 * @note This function exits.
 */
function islandora_rest_relationship($pid) {
  module_load_include('inc', 'islandora_rest', 'includes/utilities');
  print islandora_rest_get_response('relationship', array('pid' => $pid));
  exit();
}

/**
 * Rest end-point for making SOLR queries.
 *
 * @note This function exits.
 */
function islandora_rest_solr($query = NULL) {
  module_load_include('inc', 'islandora_rest', 'includes/utilities');
  print islandora_rest_get_response('solr', array('query' => $query));
  exit();
}
